package com.gemini.BusTicketBookingSystem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * Entity class representing an address in the database.
 * Maps to the "addresses" table. Used to store location details
 * for offices, customers, drivers, and trip boarding/dropping points.
 */
@Entity
@Table(name = "addresses")
@Builder
public class Addresses{

    /** Unique identifier for the address, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "address_id")
    private Integer addressId;

    /** Street address line (e.g., "123 Main Street") */
    @NotBlank(message = "Address is required")
    @Column(name = "address", nullable = false)
    private String address;

    /** City name (e.g., "Chennai") */
    @NotBlank(message = "City is required")
    @Column(name = "city", nullable = false)
    private String city;

    /** State name (e.g., "Tamil Nadu") */
    @NotBlank(message = "State is required")
    @Column(name = "state", nullable = false)
    private String state;

    /** Postal/Zip code (e.g., "600001"), max 10 characters */
    @NotBlank(message = "Zip code is required")
    @Column(name = "zip_code", nullable = false, length = 10)
    private String zipCode;

    /** Gets the address ID */
    public Integer getAddressId() {
        return addressId;
    }

    /** Sets the address ID */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /** Gets the street address */
    public String getAddress() {
        return address;
    }

    /** Sets the street address */
    public void setAddress(String address) {
        this.address = address;
    }

    /** Gets the city name */
    public String getCity() {
        return city;
    }

    /** Sets the city name */
    public void setCity(String city) {
        this.city = city;
    }

    /** Gets the state name */
    public String getState() {
        return state;
    }

    /** Sets the state name */
    public void setState(String state) {
        this.state = state;
    }

    /** Gets the zip code */
    public String getZipCode() {
        return zipCode;
    }

    /** Sets the zip code */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /** Default no-args constructor required by JPA */
    public Addresses() {
    }

    /** All-args constructor for creating an address with all fields */
    public Addresses(Integer addressId, String address, String city, String state, String zipCode) {
        this.addressId = addressId;
        this.address = address;
        this.city = city;
        this.state = state;
        this.zipCode = zipCode;
    }
}