package com.gemini.BusTicketBookingSystem.entity;


import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * Entity class representing a travel agency in the database.
 * Maps to the "agencies" table. An agency is the top-level business entity
 * that owns multiple offices, buses, and drivers.
 */
@Entity
@Table(name = "agencies")
 @Builder
/*
 * - This entity represents the Agency table/object stored in PostgreSQL.
 * - JPA annotations such as @Entity, @Id, @Column, @ManyToOne, and @OneToMany explain how Java fields map to database columns and relationships.
 * - Repositories save and read this entity; services convert it to DTOs before sending data back to the frontend.
 */
public class Agency {

    /** Unique identifier for the agency, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "agency_id")
    private Integer agencyId;

    /** Name of the travel agency (e.g., "VRL Travels") */
    @NotBlank(message = "Agency name is required")
    @Column(name = "name", nullable = false)
    private String name;

    /** Name of the primary contact person for the agency, max 30 characters */
    @NotBlank(message = "Contact person name is required")
    @Column(name = "contact_person_name", nullable = false, length = 30)
    private String contactPersonName;

    /** Email address of the agency, validated for proper email format */
    @Email(message = "Invalid email format")
    @NotBlank(message = "Email is required")
    @Column(name = "email", nullable = false)
    private String email;

    /** Phone number of the agency, max 10 characters */
    @NotBlank(message = "Phone is required")
    @Column(name = "phone", nullable = false, length = 10)
    private String phone;

    /** Gets the agency ID */
    public Integer getAgencyId() {
        return agencyId;
    }

    /** Sets the agency ID */
    public void setAgencyId(Integer agencyId) {
        this.agencyId = agencyId;
    }

    /** Gets the agency name */
    public String getName() {
        return name;
    }

    /** Sets the agency name */
    public void setName(String name) {
        this.name = name;
    }

    /** Gets the contact person's name */
    public String getContactPersonName() {
        return contactPersonName;
    }

    /** Sets the contact person's name */
    public void setContactPersonName(String contactPersonName) {
        this.contactPersonName = contactPersonName;
    }

    /** Gets the email address */
    public String getEmail() {
        return email;
    }

    /** Sets the email address */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Gets the phone number */
    public String getPhone() {
        return phone;
    }

    /** Sets the phone number */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Default no-args constructor required by JPA */
    public Agency() {
    }

    /** All-args constructor for creating an agency with all fields */
    public Agency(Integer agencyId, String name, String contactPersonName, String email, String phone) {
        this.agencyId = agencyId;
        this.name = name;
        this.contactPersonName = contactPersonName;
        this.email = email;
        this.phone = phone;
    }
}