package com.gemini.BusTicketBookingSystem.entity;


import jakarta.persistence.*;
import lombok.*;

/**
 * Entity class representing a branch office of a travel agency.
 * Maps to the "agency_offices" table. Each agency can have multiple offices
 * in different locations, and each office manages its own buses and drivers.
 */
@Entity
@Table(name = "agency_offices")
 @Builder
public class AgencyOffice {

    /** Unique identifier for the office, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "office_id")
    private Integer officeId;

    /** The agency this office belongs to (Many offices can belong to one agency) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "agency_id", nullable = false)
    private Agency agency;

    /** Email address of this specific office, max 100 characters */
    @Column(name = "office_mail", length = 100)
    private String officeMail;

    /** Name of the contact person at this office, max 50 characters */
    @Column(name = "office_contact_person_name", length = 50)
    private String officeContactPersonName;

    /** Contact phone number for this office, max 10 characters */
    @Column(name = "office_contact_number", length = 10)
    private String officeContactNumber;

    /** Physical address of this office (linked to the Addresses table) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "office_address_id")
    private Addresses officeAddress;

    /** Gets the office ID */
    public Integer getOfficeId() {
        return officeId;
    }

    /** Sets the office ID */
    public void setOfficeId(Integer officeId) {
        this.officeId = officeId;
    }

    /** Gets the parent agency */
    public Agency getAgency() {
        return agency;
    }

    /** Sets the parent agency */
    public void setAgency(Agency agency) {
        this.agency = agency;
    }

    /** Gets the office email */
    public String getOfficeMail() {
        return officeMail;
    }

    /** Sets the office email */
    public void setOfficeMail(String officeMail) {
        this.officeMail = officeMail;
    }

    /** Gets the office contact person's name */
    public String getOfficeContactPersonName() {
        return officeContactPersonName;
    }

    /** Sets the office contact person's name */
    public void setOfficeContactPersonName(String officeContactPersonName) {
        this.officeContactPersonName = officeContactPersonName;
    }

    /** Gets the office contact number */
    public String getOfficeContactNumber() {
        return officeContactNumber;
    }

    /** Sets the office contact number */
    public void setOfficeContactNumber(String officeContactNumber) {
        this.officeContactNumber = officeContactNumber;
    }

    /** Gets the office physical address */
    public Addresses getOfficeAddress() {
        return officeAddress;
    }

    /** Sets the office physical address */
    public void setOfficeAddress(Addresses officeAddress) {
        this.officeAddress = officeAddress;
    }

    /** Default no-args constructor required by JPA */
    public AgencyOffice() {
    }

    /** All-args constructor for creating an office with all fields */
    public AgencyOffice(Integer officeId, Agency agency, String officeMail, String officeContactPersonName, String officeContactNumber, Addresses officeAddress) {
        this.officeId = officeId;
        this.agency = agency;
        this.officeMail = officeMail;
        this.officeContactPersonName = officeContactPersonName;
        this.officeContactNumber = officeContactNumber;
        this.officeAddress = officeAddress;
    }
}