package com.gemini.BusTicketBookingSystem.entity;

//import com.busticket.enums.BookingStatus;
import com.gemini.BusTicketBookingSystem.enums.BookingStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

/**
 * Entity class representing a seat booking on a trip.
 * Maps to the "bookings" table. A booking links a customer to a specific
 * seat on a specific trip. The status tracks whether the seat is booked or available.
 */
@Entity
@Table(name = "bookings")
@Builder
/*
 * - This entity represents the Booking table/object stored in PostgreSQL.
 * - JPA annotations such as @Entity, @Id, @Column, @ManyToOne, and @OneToMany explain how Java fields map to database columns and relationships.
 * - Repositories save and read this entity; services convert it to DTOs before sending data back to the frontend.
 */
public class Booking {

    /** Unique identifier for the booking, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "booking_id")
    private Integer bookingId;

    /** The trip this booking is for (Many bookings can belong to one trip) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trip_id")
    private Trip trip;

    /** The customer who made this booking (Many bookings can belong to one customer) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    private Customer customer;

    /** The seat number assigned to this booking (1 to bus capacity) */
    @NotNull(message = "Seat number is required")
    @Column(name = "seat_number", nullable = false)
    private Integer seatNumber;

    /** Placeholder setter for booking status as string (not currently used) */
    public void setBookingStatus(String confirmed) {
    }

    /** Current status of the booking (Booked or Available). Defaults to Available. */
    @Builder.Default
    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    private BookingStatus status = BookingStatus.Available;

    /** Gets the booking ID */
    public Integer getBookingId() {
        return bookingId;
    }

    /** Sets the booking ID */
    public void setBookingId(Integer bookingId) {
        this.bookingId = bookingId;
    }

    /** Gets the trip associated with this booking */
    public Trip getTrip() {
        return trip;
    }

    /** Sets the trip for this booking */
    public void setTrip(Trip trip) {
        this.trip = trip;
    }

    /** Gets the customer who made this booking */
    public Customer getCustomer() {
        return customer;
    }

    /** Sets the customer for this booking */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /** Gets the seat number */
    public Integer getSeatNumber() {
        return seatNumber;
    }

    /** Sets the seat number */
    public void setSeatNumber(Integer seatNumber) {
        this.seatNumber = seatNumber;
    }

    /** Gets the booking status (Booked or Available) */
    public BookingStatus getStatus() {
        return status;
    }

    /** Sets the booking status */
    public void setStatus(BookingStatus status) {
        this.status = status;
    }

    /** Default no-args constructor required by JPA */
    public Booking() {
    }

    /** All-args constructor for creating a booking with all fields */
    public Booking(Integer bookingId, Trip trip, Customer customer, Integer seatNumber, BookingStatus status) {
        this.bookingId = bookingId;
        this.trip = trip;
        this.customer = customer;
        this.seatNumber = seatNumber;
        this.status = status;
    }
}