package com.gemini.BusTicketBookingSystem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

/**
 * Entity class representing a bus in the system.
 * Maps to the "buses" table. Each bus belongs to an agency office
 * and has a registration number, seating capacity, and type (e.g., AC, Non-AC).
 */
@Entity
@Table(name = "buses")
 @Builder
/*
 * - This entity represents the Bus table/object stored in PostgreSQL.
 * - JPA annotations such as @Entity, @Id, @Column, @ManyToOne, and @OneToMany explain how Java fields map to database columns and relationships.
 * - Repositories save and read this entity; services convert it to DTOs before sending data back to the frontend.
 */
public class Bus {

    /** Unique identifier for the bus, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "bus_id")
    private Integer busId;

    /** The agency office this bus belongs to (Many buses can belong to one office) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "office_id", nullable = false)
    private AgencyOffice office;

    /** Vehicle registration number (e.g., "TN01AB1234"), must be unique, max 20 chars */
    @NotBlank(message = "Registration number is required")
    @Column(name = "registration_number", nullable = false, length = 20)
    private String registrationNumber;

    /** Total number of seats in the bus, must be at least 1 */
    @NotNull(message = "Capacity is required")
    @Min(value = 1, message = "Capacity must be at least 1")
    @Column(name = "capacity", nullable = false)
    private Integer capacity;

    /** Type of bus (e.g., "AC Sleeper", "Non-AC Seater"), max 30 characters */
    @NotBlank(message = "Bus type is required")
    @Column(name = "type", nullable = false, length = 30)
    private String type;


    /** Gets the bus ID */
    public Integer getBusId() {
        return busId;
    }

    /** Sets the bus ID */
    public void setBusId(Integer busId) {
        this.busId = busId;
    }

    /** Gets the office this bus belongs to */
    public AgencyOffice getOffice() {
        return office;
    }

    /** Sets the office for this bus */
    public void setOffice(AgencyOffice office) {
        this.office = office;
    }

    /** Gets the registration number */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /** Sets the registration number */
    public void setRegistrationNumber(String registrationNumber) {
        this.registrationNumber = registrationNumber;
    }

    /** Gets the seating capacity */
    public Integer getCapacity() {
        return capacity;
    }

    /** Sets the seating capacity */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /** Gets the bus type */
    public String getType() {
        return type;
    }

    /** Sets the bus type */
    public void setType(String type) {
        this.type = type;
    }

    /** Default no-args constructor required by JPA */
    public Bus() {
    }

    /** All-args constructor for creating a bus with all fields */
    public Bus(Integer busId, AgencyOffice office, String registrationNumber, Integer capacity, String type) {
        this.busId = busId;
        this.office = office;
        this.registrationNumber = registrationNumber;
        this.capacity = capacity;
        this.type = type;
    }
}