package com.gemini.BusTicketBookingSystem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * Entity class representing a customer in the system.
 * Maps to the "customers" table. A customer can book seats on trips,
 * make payments, and write reviews. Email and phone must be unique.
 */
@Entity
@Table(name = "customers")
 @Builder
/*
 * - This entity represents the Customer table/object stored in PostgreSQL.
 * - JPA annotations such as @Entity, @Id, @Column, @ManyToOne, and @OneToMany explain how Java fields map to database columns and relationships.
 * - Repositories save and read this entity; services convert it to DTOs before sending data back to the frontend.
 */
public class Customer {

    /** Unique identifier for the customer, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "customer_id")
    private Integer customerId;

    /** Full name of the customer */
    @NotBlank(message = "Name is required")
    @Column(name = "name", nullable = false)
    private String name;

    /** Email address of the customer, must be unique and valid format */
    @Email(message = "Invalid email format")
    @NotBlank(message = "Email is required")
    @Column(name = "email", nullable = false)
    private String email;

    /** Phone number of the customer, must be unique, max 15 characters */
    @NotBlank(message = "Phone is required")
    @Column(name = "phone", nullable = false, length = 15)
    private String phone;

    /** Residential address of the customer (linked to the Addresses table) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_id")
    private Addresses address;

    /** Gets the customer ID */
    public Integer getCustomerId() {
        return customerId;
    }

    /** Sets the customer ID */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /** Gets the customer's name */
    public String getName() {
        return name;
    }

    /** Sets the customer's name */
    public void setName(String name) {
        this.name = name;
    }

    /** Gets the customer's email */
    public String getEmail() {
        return email;
    }

    /** Sets the customer's email */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Gets the customer's phone number */
    public String getPhone() {
        return phone;
    }

    /** Sets the customer's phone number */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Gets the customer's address */
    public Addresses getAddress() {
        return address;
    }

    /** Sets the customer's address */
    public void setAddress(Addresses address) {
        this.address = address;
    }

    /** Default no-args constructor required by JPA */
    public Customer() {
    }

    /** All-args constructor for creating a customer with all fields */
    public Customer(Integer customerId, String name, String email, String phone, Addresses address) {
        this.customerId = customerId;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.address = address;
    }
}