package com.gemini.BusTicketBookingSystem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * Entity class representing a bus driver in the system.
 * Maps to the "drivers" table. Each driver is assigned to an agency office
 * and has a unique license number. A driver can be assigned to trips.
 */
@Entity
@Table(name = "drivers")
@Builder
/*
 * - This entity represents the Driver table/object stored in PostgreSQL.
 * - JPA annotations such as @Entity, @Id, @Column, @ManyToOne, and @OneToMany explain how Java fields map to database columns and relationships.
 * - Repositories save and read this entity; services convert it to DTOs before sending data back to the frontend.
 */
public class Driver {

    /** Unique identifier for the driver, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "driver_id")
    private Integer driverId;

    /** Driving license number (must be unique), max 20 characters */
    @NotBlank(message = "License number is required")
    @Column(name = "license_number", nullable = false, length = 20)
    private String licenseNumber;

    /** Full name of the driver */
    @NotBlank(message = "Name is required")
    @Column(name = "name", nullable = false)
    private String name;

    /** Phone number of the driver, max 15 characters */
    @NotBlank(message = "Phone is required")
    @Column(name = "phone", nullable = false, length = 15)
    private String phone;

    /** The agency office this driver works at (Many drivers per office) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "office_id")
    private AgencyOffice office;

    /** Residential address of the driver (linked to the Addresses table) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_id")
    private Addresses address;

    /** Gets the driver ID */
    public Integer getDriverId() {
        return driverId;
    }

    /** Sets the driver ID */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /** Gets the license number */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /** Sets the license number */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber;
    }

    /** Gets the driver's name */
    public String getName() {
        return name;
    }

    /** Sets the driver's name */
    public void setName(String name) {
        this.name = name;
    }

    /** Gets the driver's phone number */
    public String getPhone() {
        return phone;
    }

    /** Sets the driver's phone number */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Gets the office this driver is assigned to */
    public AgencyOffice getOffice() {
        return office;
    }

    /** Sets the office for this driver */
    public void setOffice(AgencyOffice office) {
        this.office = office;
    }

    /** Gets the driver's residential address */
    public Addresses getAddress() {
        return address;
    }

    /** Sets the driver's residential address */
    public void setAddress(Addresses address) {
        this.address = address;
    }

    /** Default no-args constructor required by JPA */
    public Driver() {
    }

    /** All-args constructor for creating a driver with all fields */
    public Driver(Integer driverId, String licenseNumber, String name, String phone, AgencyOffice office, Addresses address) {
        this.driverId = driverId;
        this.licenseNumber = licenseNumber;
        this.name = name;
        this.phone = phone;
        this.office = office;
        this.address = address;
    }
}