package com.gemini.BusTicketBookingSystem.entity;

//import com.busticket.enums.PaymentStatus;
import com.gemini.BusTicketBookingSystem.enums.PaymentStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity class representing a payment made for a booking.
 * Maps to the "payments" table. Each payment is linked to one booking
 * and one customer. Tracks the amount, date, and status of the payment.
 */
@Entity
@Table(name = "payments")
 @Builder
/*
 * - This entity represents the Payment table/object stored in PostgreSQL.
 * - JPA annotations such as @Entity, @Id, @Column, @ManyToOne, and @OneToMany explain how Java fields map to database columns and relationships.
 * - Repositories save and read this entity; services convert it to DTOs before sending data back to the frontend.
 */
public class Payment {

    /** Unique identifier for the payment, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "payment_id")
    private Integer paymentId;

    /** The booking this payment is for (each booking has at most one payment) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "booking_id", nullable = false)
    private Booking booking;

    /** The customer who made this payment */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id")
    private Customer customer;

    /** Payment amount in decimal format (e.g., 500.00) */
    @Column(name = "amount", precision = 10, scale = 2)
    private BigDecimal amount;

    /** Timestamp when the payment was processed */
    @Column(name = "payment_date")
    private LocalDateTime paymentDate;


    /** Status of the payment (Success, Failed, or Pending) */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status")
    private PaymentStatus paymentStatus;

    /** Gets the payment ID */
    public Integer getPaymentId() {
        return paymentId;
    }

    /** Sets the payment ID */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /** Gets the booking linked to this payment */
    public Booking getBooking() {
        return booking;
    }

    /** Sets the booking for this payment */
    public void setBooking(Booking booking) {
        this.booking = booking;
    }

    /** Gets the customer who made the payment */
    public Customer getCustomer() {
        return customer;
    }

    /** Sets the customer for this payment */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /** Gets the payment amount */
    public BigDecimal getAmount() {
        return amount;
    }

    /** Sets the payment amount */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /** Gets the payment date/time */
    public LocalDateTime getPaymentDate() {
        return paymentDate;
    }

    /** Sets the payment date/time */
    public void setPaymentDate(LocalDateTime paymentDate) {
        this.paymentDate = paymentDate;
    }

    /** Gets the payment status */
    public PaymentStatus getPaymentStatus() {
        return paymentStatus;
    }

    /** Sets the payment status */
    public void setPaymentStatus(PaymentStatus paymentStatus) {
        this.paymentStatus = paymentStatus;
    }

    /** Default no-args constructor required by JPA */
    public Payment() {
    }

    /** All-args constructor for creating a payment with all fields */
    public Payment(Integer paymentId, Booking booking, Customer customer, BigDecimal amount, LocalDateTime paymentDate, PaymentStatus paymentStatus) {
        this.paymentId = paymentId;
        this.booking = booking;
        this.customer = customer;
        this.amount = amount;
        this.paymentDate = paymentDate;
        this.paymentStatus = paymentStatus;
    }
}