package com.gemini.BusTicketBookingSystem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Entity class representing a customer's review for a completed trip.
 * Maps to the "reviews" table. Each review has a rating (1-5 stars),
 * an optional text comment, and is linked to a specific trip and customer.
 */
@Entity
@Table(name = "reviews")
 @Builder
/*
 * - This entity represents the Review table/object stored in PostgreSQL.
 * - JPA annotations such as @Entity, @Id, @Column, @ManyToOne, and @OneToMany explain how Java fields map to database columns and relationships.
 * - Repositories save and read this entity; services convert it to DTOs before sending data back to the frontend.
 */
public class Review {

    /** Unique identifier for the review, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "review_id")
    private Integer reviewId;

    /** The customer who wrote this review */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    /** The trip being reviewed */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "trip_id", nullable = false)
    private Trip trip;

    /** Rating given by the customer (1 = worst, 5 = best) */
    @NotNull(message = "Rating is required")
    @Min(value = 1, message = "Rating must be at least 1")
    @Max(value = 5, message = "Rating must be at most 5")
    @Column(name = "rating", nullable = false)
    private Integer rating;

    /** Optional text comment/feedback from the customer */
    @Column(name = "comment", columnDefinition = "TEXT")
    private String comment;

    /** Timestamp when the review was submitted */
    @Column(name = "review_date")
    private LocalDateTime reviewDate;

    /** Gets the review ID */
    public Integer getReviewId() {
        return reviewId;
    }

    /** Sets the review ID */
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

    /** Gets the customer who wrote this review */
    public Customer getCustomer() {
        return customer;
    }

    /** Sets the customer for this review */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    /** Gets the trip being reviewed */
    public Trip getTrip() {
        return trip;
    }

    /** Sets the trip for this review */
    public void setTrip(Trip trip) {
        this.trip = trip;
    }

    /** Gets the rating value */
    public Integer getRating() {
        return rating;
    }

    /** Sets the rating value */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /** Gets the review comment text */
    public String getComment() {
        return comment;
    }

    /** Sets the review comment text */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /** Gets the review submission date */
    public LocalDateTime getReviewDate() {
        return reviewDate;
    }

    /** Sets the review submission date */
    public void setReviewDate(LocalDateTime reviewDate) {
        this.reviewDate = reviewDate;
    }

    /** Default no-args constructor required by JPA */
    public Review() {
    }

    /** All-args constructor for creating a review with all fields */
    public Review(Integer reviewId, Customer customer, Trip trip, Integer rating, String comment, LocalDateTime reviewDate) {
        this.reviewId = reviewId;
        this.customer = customer;
        this.trip = trip;
        this.rating = rating;
        this.comment = comment;
        this.reviewDate = reviewDate;
    }
}