package com.gemini.BusTicketBookingSystem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * Entity class representing a bus route from one city to another.
 * Maps to the "routes" table. Each route defines a source city,
 * destination city, number of break/stop points, and estimated duration.
 */
@Entity
@Table(name = "routes")
 @Builder
/*
 * - This entity represents the Route table/object stored in PostgreSQL.
 * - JPA annotations such as @Entity, @Id, @Column, @ManyToOne, and @OneToMany explain how Java fields map to database columns and relationships.
 * - Repositories save and read this entity; services convert it to DTOs before sending data back to the frontend.
 */
public class Route {

    /** Unique identifier for the route, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "route_id")
    private Integer routeId;

    /** Source/departure city name (e.g., "Chennai") */
    @NotBlank(message = "From city is required")
    @Column(name = "from_city", nullable = false)
    private String fromCity;

    /** Destination/arrival city name (e.g., "Bangalore") */
    @NotBlank(message = "To city is required")
    @Column(name = "to_city", nullable = false)
    private String toCity;

    /** Number of intermediate stops/break points on this route */
    @Column(name = "break_points")
    private Integer breakPoints;

    /** Estimated travel duration in minutes */
    @Column(name = "duration")
    private Integer duration;

    /** Gets the route ID */
    public Integer getRouteId() {
        return routeId;
    }

    /** Sets the route ID */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /** Gets the departure city */
    public String getFromCity() {
        return fromCity;
    }

    /** Sets the departure city */
    public void setFromCity(String fromCity) {
        this.fromCity = fromCity;
    }

    /** Gets the destination city */
    public String getToCity() {
        return toCity;
    }

    /** Sets the destination city */
    public void setToCity(String toCity) {
        this.toCity = toCity;
    }

    /** Gets the number of break points */
    public Integer getBreakPoints() {
        return breakPoints;
    }

    /** Sets the number of break points */
    public void setBreakPoints(Integer breakPoints) {
        this.breakPoints = breakPoints;
    }

    /** Gets the duration in minutes */
    public Integer getDuration() {
        return duration;
    }

    /** Sets the duration in minutes */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /** Default no-args constructor required by JPA */
    public Route() {
    }

    /** All-args constructor for creating a route with all fields */
    public Route(Integer routeId, String fromCity, String toCity, Integer breakPoints, Integer duration) {
        this.routeId = routeId;
        this.fromCity = fromCity;
        this.toCity = toCity;
        this.breakPoints = breakPoints;
        this.duration = duration;
    }
}