package com.gemini.BusTicketBookingSystem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity class representing a bus trip in the system.
 * Maps to the "trips" table. A trip is the core booking unit — it connects
 * a route, a bus, drivers, boarding/dropping addresses, schedule, and fare.
 * Customers book seats on trips, and reviews are submitted for trips.
 */
@Entity
@Table(name = "trips")
@Builder
public class Trip {

    /** Unique identifier for the trip, auto-generated by the database */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "trip_id")
    private Integer tripId;

    /** The route this trip follows (from city A to city B) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "route_id", nullable = false)
    private Route route;

    /** The bus assigned to this trip */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bus_id", nullable = false)
    private Bus bus;

    /** The address where passengers board the bus */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "boarding_address_id", nullable = false)
    private Addresses boardingAddress;

    /** The address where passengers are dropped off */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dropping_address_id", nullable = false)
    private Addresses droppingAddress;

    /** Scheduled departure date and time */
    @NotNull(message = "Departure time is required")
    @Column(name = "departure_time", nullable = false)
    private LocalDateTime departureTime;

    /** Scheduled arrival date and time */
    @NotNull(message = "Arrival time is required")
    @Column(name = "arrival_time", nullable = false)
    private LocalDateTime arrivalTime;

    /** Primary driver assigned to this trip (required) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "driver1_driver_id", nullable = false)
    private Driver driver1;

    /** Secondary/relief driver (optional, for long trips) */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "driver2_driver_id", nullable = true)
    private Driver driver2;

    /** Number of seats still available for booking (decreases as seats are booked) */
    @NotNull(message = "Available seats is required")
    @Column(name = "available_seats", nullable = false)
    private Integer availableSeats;

    /** Ticket fare/price per seat for this trip */
    @NotNull(message = "Fare is required")
    @Column(name = "fare", nullable = false, precision = 10, scale = 2)
    private BigDecimal fare;

    /** The date of the trip (stored as start of day) */
    @NotNull(message = "Trip date is required")
    @Column(name = "trip_date", nullable = false)
    private LocalDateTime tripDate;

    /** Whether the trip is closed for new bookings (defaults to false) */
    @Builder.Default
    @Column(name = "is_closed")
    private Boolean isClosed = false;

    /** Gets the primary driver */
    public Driver getDriver1() {
        return driver1;
    }

    /** Sets the primary driver */
    public void setDriver1(Driver driver1) {
        this.driver1 = driver1;
    }

    /** Gets the trip ID */
    public Integer getTripId() {
        return tripId;
    }

    /** Sets the trip ID */
    public void setTripId(Integer tripId) {
        this.tripId = tripId;
    }

    /** Gets the route for this trip */
    public Route getRoute() {
        return route;
    }

    /** Sets the route for this trip */
    public void setRoute(Route route) {
        this.route = route;
    }

    /** Gets the bus assigned to this trip */
    public Bus getBus() {
        return bus;
    }

    /** Sets the bus for this trip */
    public void setBus(Bus bus) {
        this.bus = bus;
    }

    /** Gets the boarding address */
    public Addresses getBoardingAddress() {
        return boardingAddress;
    }

    /** Sets the boarding address */
    public void setBoardingAddress(Addresses boardingAddress) {
        this.boardingAddress = boardingAddress;
    }

    /** Gets the dropping address */
    public Addresses getDroppingAddress() {
        return droppingAddress;
    }

    /** Sets the dropping address */
    public void setDroppingAddress(Addresses droppingAddress) {
        this.droppingAddress = droppingAddress;
    }

    /** Gets the departure time */
    public LocalDateTime getDepartureTime() {
        return departureTime;
    }

    /** Sets the departure time */
    public void setDepartureTime(LocalDateTime departureTime) {
        this.departureTime = departureTime;
    }

    /** Gets the arrival time */
    public LocalDateTime getArrivalTime() {
        return arrivalTime;
    }

    /** Sets the arrival time */
    public void setArrivalTime(LocalDateTime arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    /** Gets the secondary driver */
    public Driver getDriver2() {
        return driver2;
    }

    /** Sets the secondary driver */
    public void setDriver2(Driver driver2) {
        this.driver2 = driver2;
    }

    /** Gets the number of available seats */
    public Integer getAvailableSeats() {
        return availableSeats;
    }

    /** Sets the number of available seats */
    public void setAvailableSeats(Integer availableSeats) {
        this.availableSeats = availableSeats;
    }

    /** Gets the fare per seat */
    public BigDecimal getFare() {
        return fare;
    }

    /** Sets the fare per seat */
    public void setFare(BigDecimal fare) {
        this.fare = fare;
    }

    /** Gets the trip date */
    public LocalDateTime getTripDate() {
        return tripDate;
    }

    /** Sets the trip date */
    public void setTripDate(LocalDateTime tripDate) {
        this.tripDate = tripDate;
    }

    /** Gets whether the trip is closed */
    public Boolean getClosed() {
        return isClosed;
    }

    /** Sets whether the trip is closed */
    public void setClosed(Boolean closed) {
        isClosed = closed;
    }

    /** Default no-args constructor required by JPA */
    public Trip() {
    }

    /** All-args constructor for creating a trip with all fields */
    public Trip(Integer tripId, Route route, Bus bus, Addresses boardingAddress, Addresses droppingAddress,
            LocalDateTime departureTime, LocalDateTime arrivalTime, Driver driver1, Driver driver2,
            Integer availableSeats, BigDecimal fare, LocalDateTime tripDate, Boolean isClosed) {
        this.tripId = tripId;
        this.route = route;
        this.bus = bus;
        this.boardingAddress = boardingAddress;
        this.droppingAddress = droppingAddress;
        this.departureTime = departureTime;
        this.arrivalTime = arrivalTime;
        this.driver1 = driver1;
        this.driver2 = driver2;
        this.availableSeats = availableSeats;
        this.fare = fare;
        this.tripDate = tripDate;
        this.isClosed = isClosed;
    }
}